name: Parallel Build
on: push
jobs:
  addtoCart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          command: npm run test:addToCart

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - addtoCart
          path: cypress/reports/html

  registerflow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          command: npm run test:register

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - register
          path: cypress/reports/html
    